org: amichaimlevy
app: snippet-aggregator
service: snippet-aggeregator
frameworkVersion: '3'

provider:
  httpApi:
    cors: true
  name: aws
  runtime: python3.8
  stage: dev
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - arn:aws:dynamodb:us-east-1:276830396462:table/TA_Snippets
            - arn:aws:dynamodb:us-east-1:276830396462:table/TA_Users
            - arn:aws:dynamodb:us-east-1:276830396462:table/TA_Notebooks

  environment:
    TA_Snippets: TA_Snippets

functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /
          method: get

  newSnippet:
    handler: handler.newSnippet
    events:
      - httpApi:
          path: /newSnippet
          method: post

  newNotebook:
    handler: handler.newNotebook
    events:
      - httpApi:
          path: /newNotebook
          method: post

  getNotebook:
    handler: handler.getNotebook
    events:
      - httpApi:
          path: /getNotebook
          method: get

  getNotebooks:
    handler: handler.getNotebooks
    events:
      - httpApi:
          path: /getNotebooks
          method: get

  getNotebookInfo:
    handler: handler.getNotebookInfo
    events:
      - httpApi:
          path: /getNotebookInfo
          method: get

  getSnippet:
    handler: handler.getSnippet
    events:
      - httpApi:
          path: /getSnippet
          method: get

  updateNotebook:
    handler: handler.updateNotebook
    events:
      - httpApi:
          path: /updateNotebook
          method: put

  deleteSnippet:
    handler: handler.deleteSnippet
    events:
      - httpApi:
          path: /deleteSnippet
          method: DELETE

plugins:
  - serverless-python-requirements
